#!/usr/bin/env bash
who=$(whoami)
figlet distcontinue
echo " Xenta Distro Builder"
echo " "
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts none /dev/pts
export HOME=/root
export LC_ALL=C
