#!/usr/bin/env bash
versi="1.3LTS"
codename=arok
de=xfce
jahitan=jh000
dir_project=/home/$(whoami)/xentaos/pengembangan/i386/
dir_root=/home/$(whoami)/xentaos/pengembangan/i386/root
dir_dvd=/home/$(whoami)/xentaos/pengembangan/i386/dvd
dir_iso=/home/$(whoami)/xentaos/perilisan/i386/iso
dir_backup=/media/$(whoami)/backup/iso
figlet .iso
echo " Xenta Distro Builder"
cd $dir_project
sudo cp $dir_dvd/casper/filesystem.manifest $dir_dvd/casper/filesystem.manifest-desktop
cd $dir_iso
sudo rm MD5SUMS
find -type f -print0 | sudo xargs -0 md5sum | grep -v isolinux/boot.cat | sudo tee MD5SUMS
cd $dir_project
sudo mksquashfs root $dir_dvd/casper/filesystem.squashfs -b 1048576 -comp xz -Xdict-size 100%
sudo mkisofs -r -V "xentaos-1.3LTS-xfce-i386" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o $dir_iso/xentaos-1.3LTS-xfce-i386-$jahitan.iso $dir_dvd
cd $dir_iso
sudo chmod 777 xentaos-1.3LTS-xfce-i386-$jahitan.iso
isohybrid xentaos-1.3LTS-xfce-i386-$jahitan.iso
md5sum xentaos-1.3LTS-xfce-i386-$jahitan.iso   >   xentaos-1.3LTS-xfce-i386-$jahitan.iso.md5msum
sha1sum xentaos-1.3LTS-xfce-i386-$jahitan.iso  >   xentaos-1.3LTS-xfce-i386-$jahitan.iso.sha1sum
sha2sum xentaos-1.3LTS-xfce-i386-$jahitan.iso  >   xentaos-1.3LTS-xfce-i386-$jahitan.iso.sha2shum
